// <auto-generated />
using System;
using Games_Report__CodeFirst_;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Games_Report__CodeFirst_.Migrations
{
    [DbContext(typeof(GameStorageContext))]
    [Migration("20210916050538_AddGameInfoCountOfSoldCopiesColumn")]
    partial class AddGameInfoCountOfSoldCopiesColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Games_Report__CodeFirst_.Entities.GameInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CountOfSoldCopies")
                        .HasColumnType("int");

                    b.Property<string>("Creator")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GameMode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Style")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("GameInfos");

                    b.HasData(
                        new
                        {
                            Id = -1,
                            CountOfSoldCopies = 0,
                            Creator = "PCF",
                            GameMode = "single",
                            ReleaseDate = new DateTime(2021, 9, 16, 8, 5, 38, 198, DateTimeKind.Local).AddTicks(4940),
                            Style = "RPG",
                            Title = "12"
                        },
                        new
                        {
                            Id = -2,
                            CountOfSoldCopies = 0,
                            Creator = "Bioware",
                            GameMode = "single",
                            ReleaseDate = new DateTime(2021, 9, 16, 8, 5, 38, 200, DateTimeKind.Local).AddTicks(2902),
                            Style = "Shooter",
                            Title = "1676"
                        },
                        new
                        {
                            Id = -3,
                            CountOfSoldCopies = 0,
                            Creator = "P56",
                            GameMode = "single",
                            ReleaseDate = new DateTime(2021, 9, 16, 8, 5, 38, 200, DateTimeKind.Local).AddTicks(2962),
                            Style = "R12",
                            Title = "121"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
